version: '2'
services:
  front:
    build: ./front
    ports:
      - "80:80"
    volumes:
      - "./front/src/:/data/src/"
      - "./front/conf:/etc/nginx/sites-available"
    command: bash -c "./start.sh"
    networks:
        tars_net:
          ipv4_address: ==project.iptemplate==.10
          ipv6_address: 2001:3984:3989::10
  api:
    build: ./api
    ports:
      - "1337:1337"
    volumes:
      - "./api/src:/data/src"
    command: "sails lift"
    networks:
        tars_net:
          ipv4_address: ==project.iptemplate==.11
          ipv6_address: 2001:3984:3969::10
  db:
    build: ./db
    ports:
      - "27017:27017"
    volumes:
      - "./db/data:/data/db"
    networks:
        tars_net:
          ipv4_address: ==project.iptemplate==.12
          ipv6_address: 2001:3984:3979::10

networks:
  tars_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: ==project.iptemplate==.0/24
        gateway: ==project.iptemplate==.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
